# Generated by Django 3.2.12 on 2023-06-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='pat_id',
            new_name='pat_name',
        ),
        migrations.CreateModel(
            name='Pat_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('pat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
