# Generated by Django 3.2.12 on 2023-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20230620_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='analysis_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='x_ray',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
