# Generated by Django 3.2.12 on 2023-06-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20230620_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diabetes', models.BooleanField(default=False)),
                ('Cancer', models.BooleanField(default=False)),
                ('Heart_Disease', models.BooleanField(default=False)),
                ('High_Blood_Pressure', models.BooleanField(default=False)),
                ('High_Cholesterol', models.BooleanField(default=False)),
                ('pat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
