# Generated by Django 3.2.12 on 2023-06-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doc_name',
            field=models.ManyToManyField(to='doctors.Doctors'),
        ),
    ]
