# Generated by Django 3.2.12 on 2023-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0005_patients_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pat_doc',
            name='doc_name',
        ),
        migrations.AddField(
            model_name='pat_doc',
            name='doc_name',
            field=models.ManyToManyField(to='doctors.Doctors'),
        ),
        migrations.RemoveField(
            model_name='pat_doc',
            name='pat_name',
        ),
        migrations.AddField(
            model_name='pat_doc',
            name='pat_name',
            field=models.ManyToManyField(to='patients.Patients'),
        ),
    ]
