# Generated by Django 3.2.12 on 2023-06-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0006_auto_20230620_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doc_name',
        ),
        migrations.AddField(
            model_name='patients',
            name='doc_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors'),
            preserve_default=False,
        ),
    ]
