# Generated by Django 3.2.12 on 2023-06-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20230620_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Pat_Doc',
        ),
    ]
