# Generated by Django 4.2.2 on 2023-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20230620_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='number',
            field=models.IntegerField(),
        ),
    ]
