# Generated by Django 3.2.12 on 2023-06-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patients_age_alter_sessions_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='analysis_image',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='x_ray',
        ),
    ]
