# Generated by Django 3.2.12 on 2023-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20230629_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='number',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together={('pat_name', 'number')},
        ),
    ]
