# Generated by Django 3.2.12 on 2023-07-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_remove_history_allergies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Bone_denisty',
            new_name='Cancer',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Cholesterol',
            new_name='High_Cholesterol',
        ),
    ]
