# Generated by Django 3.2.12 on 2023-07-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20230702_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='history',
        ),
    ]
