# Generated by Django 3.2.12 on 2023-07-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_remove_sessions_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='medical_diagnosis',
        ),
    ]
