# Generated by Django 3.2.12 on 2023-07-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_remove_sessions_medical_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Diabetes',
            field=models.BooleanField(),
        ),
    ]
