# Generated by Django 3.2.12 on 2023-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_history_diabetes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Cancer',
            new_name='Allergies',
        ),
        migrations.AddField(
            model_name='history',
            name='Bone_denisty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessions',
            name='history',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='medical_diagnoses',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
