# Generated by Django 3.2.12 on 2023-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20230702_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Diabetes',
            field=models.BooleanField(default=False),
        ),
    ]
