# Generated by Django 3.2.12 on 2023-07-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_alter_history_diabetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Allergies',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Bone_denisty',
        ),
    ]
