# Generated by Django 3.2.12 on 2023-07-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20230702_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='history',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='medical_diagnoses',
        ),
    ]
