# Generated by Django 3.2.12 on 2023-07-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20230702_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Allergies',
            new_name='cancer',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Bone_denisty',
        ),
    ]
