# Generated by Django 3.2.12 on 2023-07-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20230702_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cancer',
        ),
    ]
