# Generated by Django 3.2.12 on 2023-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_remove_history_cancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='Bone_denisty',
            field=models.BooleanField(default=False),
        ),
    ]
