# Generated by Django 3.2.12 on 2023-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_auto_20230702_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Allergies',
            new_name='Cancer',
        ),
        migrations.RemoveField(
            model_name='history',
            name='Bone_denisty',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='medical_analysis',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
