# Generated by Django 3.2.12 on 2023-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_auto_20230702_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateField(default=0.0005),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='medical_diagnose',
            field=models.TextField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
