# Generated by Django 3.2.12 on 2023-07-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20230702_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='medical_diagnose',
            new_name='analysis_image',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='date',
        ),
    ]
