# Generated by Django 3.2.12 on 2023-07-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_remove_sessions_analysis_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateField(default='1-1-2000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='medical_diagnose',
            field=models.TextField(default='cb', max_length=1000),
            preserve_default=False,
        ),
    ]
