# Generated by Django 3.2.12 on 2023-07-03 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20230702_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 3, 4, 2, 32, 341486, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
