# Generated by Django 3.2.12 on 2023-07-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_sessions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='date',
        ),
    ]
