# Generated by Django 3.2.12 on 2023-06-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='confirm_password',
            field=models.CharField(default=True, max_length=15),
            preserve_default=False,
        ),
    ]
